# Generated by Django 4.2.2 on 2023-06-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_remove_producto_cantidad_factura_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='codigo_factura',
        ),
    ]
